#!/usr/local/bin/node

let request = require("request");
let {Phrase} = require("golden-palindrome");
let url = "https://cdn.learnenough.com/phrases.txt";

String.prototype.palindrome = function() {
  phrase = new Phrase(this);
  return phrase.palindrome();
}

function Palindromes(elements) {
  return elements.filter(element => element.palindrome());
}

request(url, function(error, response, body) {
  let lines = body.split("\n");
  console.log("palindrome detected:", Palindromes(lines));
});
