#!/usr/local/bin/node

let fs = require("fs");
let {Phrase} = require("golden-palindrome");
let text = fs.readFileSync("phrases.txt", "utf-8");

text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
    fs.appendFile('palindromes.txt',line, "utf-8", (err) => {if (err) throw err;});
    fs.appendFile('palindromes.txt','\n', "utf-8", (err) => {if (err) throw err;});
    }
});
