#!/usr/local/bin/node

let fs = require("fs");
let {Phrase} = require("golden-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");

text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {

    }
});

fs.open("palindromes.txt", 'w', function(err, fd) {
    if (err) {
        throw 'could not open file: ' + err;
    }
        fs.appendFile('palindromes.txt',text, "utf-8", (err) => {if (err) throw err;});
        fs.close(fd, function() {
            console.log('wrote the file successfully');
        });
});
